"""Async task delegation from Gemini Live to the main reasoning brain.

Gemini Live is never blocked waiting for Flash/Playwright. When a TASK_HANDOFF
is classified, the live session:
  1. Emits an immediate natural acknowledgement (generated by the model, not hardcoded).
  2. Calls delegate_task() — returns immediately.
  3. Transitions to WORKING state and stays conversationally present.
  4. Receives TaskEvent progress updates on a queue.
  5. When the task completes / fails, Live produces a natural result summary.

Groq is NOT on this path. It processes events asynchronously via a side channel.
"""

from __future__ import annotations

import queue
import threading
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Literal
from uuid import uuid4


class TaskStatus(str, Enum):
    CREATED = "created"
    PLAN_READY = "plan_ready"
    ACTION_STARTED = "action_started"
    ACTION_COMPLETED = "action_completed"
    VERIFICATION_STARTED = "verification_started"
    VERIFICATION_COMPLETE = "verification_complete"
    RECOVERY_STARTED = "recovery_started"
    RECOVERY_COMPLETED = "recovery_completed"
    TASK_WAITING = "task_waiting"
    TASK_COMPLETED = "task_completed"
    TASK_FAILED = "task_failed"
    USER_INTERRUPTED = "user_interrupted"


class InterruptionPolicy(str, Enum):
    MERGE = "merge"      # fold new request into ongoing task
    QUEUE = "queue"      # run new request after current task
    REPLACE = "replace"  # finish atomic action then cancel, start new task


@dataclass
class TaskEvent:
    task_id: str
    status: TaskStatus
    detail: str = ""
    timestamp: float = field(default_factory=time.monotonic)


@dataclass
class DelegatedTask:
    task_id: str
    goal: str
    urgency: Literal["low", "normal", "high"] = "normal"
    allow_browser_actions: bool = True
    submitted_at: float = field(default_factory=time.monotonic)
    events: list[TaskEvent] = field(default_factory=list)
    result: Any = None
    status: TaskStatus = TaskStatus.CREATED


class TaskDelegator:
    """Bridge between Gemini Live (producer) and orchestrator (consumer).

    The live session submits tasks and polls events; the orchestrator runs
    tasks in its own thread and pushes events back.

    Threading model:
      - submit_task()   called from the live demo / _on_event thread
      - push_event()    called from the orchestrator thread
      - on_event_fn     called back on the orchestrator thread; Live uses it
                        to nudge the model with progress context
    """

    def __init__(
        self,
        *,
        execute_fn: Callable[[DelegatedTask], None] | None = None,
        on_event_fn: Callable[[TaskEvent], None] | None = None,
    ) -> None:
        self._execute_fn = execute_fn
        self._on_event_fn = on_event_fn
        self._lock = threading.Lock()
        self._current: DelegatedTask | None = None
        self._event_q: queue.Queue[TaskEvent] = queue.Queue()
        self._worker: threading.Thread | None = None

    # ---- producer (Live side) -------------------------------------------

    def submit_task(
        self,
        goal: str,
        *,
        urgency: Literal["low", "normal", "high"] = "normal",
        allow_browser_actions: bool = True,
    ) -> DelegatedTask:
        """Submit a new task. Returns immediately.

        Interruption policy is applied relative to the current task:
          - No current task → start immediately.
          - Current task in COMPLETED/FAILED → start immediately.
          - Current task running → apply policy (default REPLACE: finish
            current atomic action, then switch).
        """
        task = DelegatedTask(
            task_id=str(uuid4())[:8],
            goal=goal,
            urgency=urgency,
            allow_browser_actions=allow_browser_actions,
        )
        with self._lock:
            old = self._current
            if old and old.status not in (
                TaskStatus.TASK_COMPLETED, TaskStatus.TASK_FAILED
            ):
                # Signal current worker to stop after its atomic action.
                self._interrupt_current(InterruptionPolicy.REPLACE, new_task=task)
            self._current = task

        self._spawn_worker(task)
        return task

    def resolve_interruption(
        self,
        new_goal: str,
        *,
        policy: InterruptionPolicy = InterruptionPolicy.REPLACE,
        allow_browser_actions: bool = True,
    ) -> DelegatedTask | None:
        """Handle mid-task user interruption with explicit policy."""
        with self._lock:
            current = self._current
            if current is None or current.status in (
                TaskStatus.TASK_COMPLETED, TaskStatus.TASK_FAILED
            ):
                return self.submit_task(new_goal, allow_browser_actions=allow_browser_actions)

            if policy == InterruptionPolicy.MERGE:
                # Append to goal; orchestrator will re-plan
                current.goal = f"{current.goal}; and also {new_goal}"
                self.push_event(TaskEvent(
                    task_id=current.task_id,
                    status=TaskStatus.USER_INTERRUPTED,
                    detail=f"merged: {new_goal}",
                ))
                return current

            if policy == InterruptionPolicy.QUEUE:
                # Not starting yet — return placeholder so Live can ack
                return DelegatedTask(
                    task_id="queued",
                    goal=new_goal,
                    status=TaskStatus.CREATED,
                )

            # REPLACE — signal and start new
            self._interrupt_current(policy, new_task=None)

        return self.submit_task(new_goal, allow_browser_actions=allow_browser_actions)

    def push_event(self, event: TaskEvent) -> None:
        """Called by the orchestrator to report task progress."""
        with self._lock:
            if self._current and self._current.task_id == event.task_id:
                self._current.events.append(event)
                self._current.status = event.status

        self._event_q.put(event)
        if self._on_event_fn is not None:
            try:
                self._on_event_fn(event)
            except Exception:  # noqa: BLE001
                pass

    def drain_events(self, timeout_s: float = 0.0) -> list[TaskEvent]:
        events: list[TaskEvent] = []
        try:
            while True:
                events.append(self._event_q.get(timeout=timeout_s))
                timeout_s = 0.0  # subsequent gets are non-blocking
        except queue.Empty:
            pass
        return events

    @property
    def current_task(self) -> DelegatedTask | None:
        with self._lock:
            return self._current

    # ---- internal -------------------------------------------------------

    def _interrupt_current(
        self,
        policy: InterruptionPolicy,
        *,
        new_task: DelegatedTask | None,
    ) -> None:
        """Signal current worker to yield after its atomic action."""
        current = self._current
        if current is None:
            return
        # The orchestrator checks this flag before starting the next action.
        current._interrupted = True  # type: ignore[attr-defined]
        self.push_event(TaskEvent(
            task_id=current.task_id,
            status=TaskStatus.USER_INTERRUPTED,
            detail=f"policy={policy.value}",
        ))

    def _spawn_worker(self, task: DelegatedTask) -> None:
        if self._execute_fn is None:
            return
        fn = self._execute_fn

        def run() -> None:
            try:
                fn(task)
            except Exception as exc:  # noqa: BLE001
                self.push_event(TaskEvent(
                    task_id=task.task_id,
                    status=TaskStatus.TASK_FAILED,
                    detail=str(exc),
                ))

        t = threading.Thread(target=run, daemon=True, name=f"task-{task.task_id}")
        with self._lock:
            self._worker = t
        t.start()
