/**
 * Compile a NavigatorConfig into site graph YAML.
 *
 * This file emits YAML and stops. It deliberately does NOT validate: alias
 * resolution, postcondition shape, and navigate targets are all checked by the
 * server's single validator (`parse_site_graph`) when the graph is pushed. Two
 * validators would drift, and the drift would surface as "worked locally,
 * rejected on push" -- the worst possible failure mode for an SDK.
 *
 * The one transformation of substance is alias -> selector: an alias that the
 * customer never declared resolves to `[data-nav="<alias>"]`. That is the whole
 * point of annotating components. The selector then survives redesigns, CSS
 * module hashes, and refactors, because the attribute moves with the element.
 */

import type { NavigatorConfig, PageConfig, ToolCall } from "./config.js";

/** How an undeclared alias becomes a selector. */
export function dataNavSelector(alias: string): string {
  return `[data-nav="${alias}"]`;
}

/** Every alias a page's flows reference, in first-seen order. */
export function referencedAliases(page: PageConfig): string[] {
  const seen = new Set<string>();
  for (const calls of Object.values(page.flows)) {
    for (const call of calls) {
      if ("selector" in call) seen.add(call.selector);
      if (call.expects.selector) seen.add(call.expects.selector);
    }
  }
  return [...seen];
}

/**
 * Declared selectors plus a `data-nav` entry for every alias used but not
 * declared. Explicit declarations always win, so a customer can override one
 * awkward element without abandoning annotations everywhere else.
 */
export function resolveSelectors(page: PageConfig): Record<string, string> {
  const out: Record<string, string> = { ...(page.selectors ?? {}) };
  for (const alias of referencedAliases(page)) {
    if (!(alias in out)) out[alias] = dataNavSelector(alias);
  }
  return out;
}

export function compile(config: NavigatorConfig): string {
  const lines: string[] = [
    "# Generated by @navigator/sdk. Do not edit by hand.",
    "# Source of truth is your navigator.config.ts.",
    "",
    `version: ${config.version ?? 1}`,
    `site: ${scalar(config.product)}`,
    `base_url: ${scalar(config.baseUrl)}`,
  ];

  if (config.persona) {
    lines.push("persona:");
    for (const [key, value] of Object.entries({
      product_name: config.persona.product_name,
      one_liner: config.persona.one_liner,
      agent_name: config.persona.agent_name,
      tone: config.persona.tone,
    })) {
      if (value !== undefined) lines.push(`  ${key}: ${scalar(value)}`);
    }
  }

  lines.push("", "pages:");
  for (const [pageId, page] of Object.entries(config.pages)) {
    lines.push(`  ${pageId}:`);
    lines.push(`    name: ${scalar(page.name)}`);
    lines.push(`    url: ${scalar(page.url ?? "")}`);

    lines.push("    selectors:");
    const selectors = resolveSelectors(page);
    if (Object.keys(selectors).length === 0) {
      lines[lines.length - 1] = "    selectors: {}";
    }
    for (const [alias, css] of Object.entries(selectors)) {
      lines.push(`      ${alias}: ${scalar(css)}`);
    }

    if (Object.keys(page.flows).length > 0) {
      lines.push("    flows:");
      for (const [flowId, calls] of Object.entries(page.flows)) {
        lines.push(`      ${flowId}:`);
        for (const call of calls) lines.push(...emitCall(call));
      }
    }
  }

  return lines.join("\n") + "\n";
}

function emitCall(call: ToolCall): string[] {
  const out = [`        - tool: ${call.tool}`];
  const indent = "          ";

  switch (call.tool) {
    case "click_element":
      out.push(`${indent}selector: ${scalar(call.selector)}`);
      break;
    case "fill_field":
      out.push(`${indent}selector: ${scalar(call.selector)}`);
      out.push(`${indent}value: ${scalar(call.value)}`);
      out.push(`${indent}source: ${call.source ?? "agent"}`);
      break;
    case "navigate":
      out.push(`${indent}page_id: ${scalar(call.page_id)}`);
      break;
    case "wait_for":
      out.push(`${indent}selector: ${scalar(call.selector)}`);
      if (call.timeout_ms !== undefined) {
        out.push(`${indent}timeout_ms: ${call.timeout_ms}`);
      }
      break;
  }

  out.push(`${indent}expects:`);
  out.push(`${indent}  check: ${call.expects.check}`);
  if (call.expects.selector !== undefined) {
    out.push(`${indent}  selector: ${scalar(call.expects.selector)}`);
  }
  if (call.expects.expected !== undefined) {
    out.push(`${indent}  expected: ${scalar(call.expects.expected)}`);
  }
  if (call.expects.timeout_ms !== undefined) {
    out.push(`${indent}  timeout_ms: ${call.expects.timeout_ms}`);
  }
  return out;
}

/**
 * Emit a YAML scalar.
 *
 * Always double-quoted with escapes. Verbose, but it means a selector containing
 * `#`, `:`, `[`, or a leading `*` can never be reinterpreted as YAML syntax --
 * and CSS selectors contain those constantly.
 */
function scalar(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
