"""Generate every documentation artifact from one source: the running code.

    python -m navigator.docs build     # write docs/index.html + fern/
    python -m navigator.docs check     # exit 1 if any committed output is stale

`check` is what makes "the docs update with every change" true. Add an endpoint,
rename a field, add a postcondition kind, and the test that calls this fails with
the command to fix it. Not discipline, not a hook -- a red test.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

from navigator.docs.html import render
from navigator.docs.mdx import render_mdx
from navigator.docs.model import DocsModel, build as build_model
from navigator.docs.snippets import SNIPPETS

REPO_ROOT = Path(__file__).resolve().parents[2]

#: Every generated artifact, relative to the repo root.
HTML_OUT = Path("docs/index.html")
OPENAPI_OUT = Path("fern/openapi/openapi.yml")
FERN_CONFIG_OUT = Path("fern/fern.config.json")
GENERATORS_OUT = Path("fern/generators.yml")
DOCS_YML_OUT = Path("fern/docs.yml")
MDX_OUT = Path("fern/pages/integration.mdx")

ORGANIZATION = "navigator"


def artifacts(model: DocsModel | None = None) -> dict[Path, str]:
    """Path -> exact content. Pure, so `check` can diff without touching disk."""
    model = model or build_model()
    return {
        HTML_OUT: render(model, SNIPPETS),
        MDX_OUT: render_mdx(model, SNIPPETS),
        OPENAPI_OUT: _openapi_yaml(model),
        FERN_CONFIG_OUT: _fern_config(),
        GENERATORS_OUT: _generators_yml(),
        DOCS_YML_OUT: _docs_yml(),
    }


def _openapi_yaml(model: DocsModel) -> str:
    """The live FastAPI schema, as YAML, for Fern to generate SDKs and docs from.

    Emitting the server's own schema is the point: the Fern SDK, the Fern hosted
    docs, and docs/index.html cannot disagree about the API, because all three are
    downstream of this one dict.
    """
    header = (
        "# Generated by `python -m navigator.docs build` from the live FastAPI\n"
        "# schema. Do not edit by hand -- tests/test_docs.py fails when this drifts.\n"
    )
    return header + yaml.safe_dump(
        json.loads(json.dumps(model.openapi)), sort_keys=False, width=100
    )


def _fern_config() -> str:
    # version "*" tracks whatever CLI is installed; pin it once the SDK is
    # published from CI, so releases are reproducible.
    return json.dumps({"organization": ORGANIZATION, "version": "*"}, indent=2) + "\n"


def _generators_yml() -> str:
    return """# yaml-language-server: $schema=https://schema.buildwithfern.dev/generators-yml.json
#
# Generated by `python -m navigator.docs build`.
#
# The spec below is itself generated from the live FastAPI app, so the SDK Fern
# produces can never describe endpoints the server doesn't serve.
#
#   npx fern-api check       # validate (no auth needed)
#   npx fern-api generate    # needs FERN_TOKEN, or --local with Docker
api:
  specs:
    - openapi: ./openapi/openapi.yml

auth-schemes:
  token:
    name: "API Key"
    header: "Authorization"
    type: "string"
    prefix: "Token "
    env: "NAVIGATOR_API_KEY"

default-group: local

groups:
  local:
    generators:
      - name: fernapi/fern-typescript-sdk
        version: 3.6.0
        output:
          location: local-file-system
          path: ../sdk/src/generated
      - name: fernapi/fern-python-sdk
        version: 4.30.0
        output:
          location: local-file-system
          path: ../clients/python
"""


def _docs_yml() -> str:
    """Fern Docs config.

    Note where the spec comes from: the `api` navigation item below carries no
    path. Fern resolves it from `api.specs` in generators.yml, which points at the
    committed ./openapi/openapi.yml -- a file, not a live URL. A live URL only
    works once something is deployed and makes every docs build depend on that
    deployment being up; the committed spec is regenerated by this same command,
    so it is never stale.
    """
    return """# Generated by `python -m navigator.docs build`.
instances:
  - url: navigator.docs.buildwithfern.com

title: Navigator AI

navigation:
  - section: Getting started
    contents:
      - page: Integration guide
        path: pages/integration.mdx
  # No spec path here: Fern takes it from `api.specs` in generators.yml.
  - api: API Reference

colors:
  # 8.1:1 on white -- clears WCAG AAA, so Fern doesn't silently adjust it.
  accentPrimary:
    light: "#0a5c31"
    dark: "#3fb950"

navbar-links:
  - type: secondary
    text: Integration guide
    url: /pages/integration
"""


def write(root: Path = REPO_ROOT) -> list[Path]:
    written = []
    for rel, content in artifacts().items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(rel)
    return written


def stale(root: Path = REPO_ROOT) -> list[Path]:
    """Which committed artifacts differ from what the code would produce now."""
    out = []
    for rel, content in artifacts().items():
        path = root / rel
        if not path.exists() or path.read_text() != content:
            out.append(rel)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m navigator.docs", description=__doc__)
    parser.add_argument("command", choices=["build", "check"])
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    args = parser.parse_args(argv)

    if args.command == "build":
        for rel in write(args.root):
            print(f"wrote {rel}")
        return 0

    outdated = stale(args.root)
    if not outdated:
        print("docs are up to date")
        return 0

    print("stale documentation:", file=sys.stderr)
    for rel in outdated:
        print(f"  {rel}", file=sys.stderr)
    print("\nfix with: python -m navigator.docs build", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
